<a href="https://colab.research.google.com/github/prajnaraipn7/EIP/blob/master/Copy_of_Eip3_Assignment2A%262B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#2A Assignment

#<font color ="maroon">Backpropagation Step by Step </font>

@prajnaraipn@gmail.com, Batch4
                      
If you are building your own neural network, you will definitely need to understand how to train it. Backpropagation is a commonly used technique for training neural network. There are many resources explaining the technique, but this post will explain backpropagation with concrete example in a very detailed colorful steps.

![alt text](https://hmkcode.github.io/images/ai/backpropagation.png)

##Overview

In this post, we will build a neural network with three layers:
*   Input layer with two inputs neurons
*   One hidden layer with two neurons
*  Output layer with a single neuron

![alt text](http://hmkcode.github.io/images/ai/nn1.png)


#Weights, weights, weights
Neural network training is about finding weights that minimize prediction error. We usually start our training with a set of randomly generated weights.Then, backpropagation is used to update the weights in an attempt to correctly map arbitrary inputs to outputs.

Our initial weights will be as following: 

<font color='blue'>w1 = 0.20, w2 = 0.02, w3 = 0.16, w4 = 0.10, w5 = 0.17 and w6 = 0.12 </font>
![alt text](https://github.com/prajnaraipn7/img/blob/master/fih.JPG?raw=true)

##Dataset
Our dataset has one sample with two inputs and one output.
![alt text](http://hmkcode.github.io/images/ai/bp_dataset.png)

Our single sample is as following inputs=[2, 3] and output=[1].
![alt text](http://hmkcode.github.io/images/ai/bp_sample.png)


##Forward Pass
We will use given weights and inputs to predict the output. Inputs are multiplied by weights; the results are then passed forward to next layer.
![alt text](https://github.com/prajnaraipn7/img/blob/master/fih3.JPG?raw=true)

$$
\begin{bmatrix}
2&3\\
\end{bmatrix}.\begin{bmatrix}
.20&.16\\
.02&.10\\
\end{bmatrix} = \begin{bmatrix}
.46&.62\\
\end{bmatrix}.\begin{bmatrix}
.17\\
.12\\
\end{bmatrix} = \begin{bmatrix}
.15\\
\end{bmatrix}
$$ 

##Calculating Error
Now, it’s time to find out how our network performed by calculating the difference between the actual output and predicted one. It’s clear that our network output, or <b>prediction</b>, is not even close to <b>actual output</b>. We can calculate the difference or the error as following.
![alt text](https://github.com/prajnaraipn7/img/blob/master/fih4.JPG?raw=true)

##Reducing Error
Our main goal of the training is to reduce the<b> error</b> or the difference between<b> prediction</b> and <b>actual output</b>. Since <b>actual output</b> is constant, “not changing”, the only way to reduce the error is to change <b>prediction</b> value. The question now is, how to change <b>prediction</b> value?

By decomposing <b>prediction</b> into its basic elements we can find that <b>weights</b> are the variable elements affecting <b>prediction</b> value. In other words, in order to change <b>prediction</b> value, we need to change <b>weights</b> values.

![alt text](http://hmkcode.github.io/images/ai/bp_prediction_elements.png)


The question now is how to <b>change\update the weights value so that the error is reduced?</b>
The answer is <b>Backpropagation!</b>

##Backpropagation
<b>Backpropagation</b>, short for “backward propagation of errors”, is a mechanism used to update the <b>weights</b> using<font color="blue"> gradient descent</font>. It calculates the gradient of the error function with respect to the neural network’s weights. The calculation proceeds backwards through the network.

> <b>Gradient descent</b> is an iterative optimization algorithm for finding the minimum of a function; in our case we want to minimize th error function. To find a local minimum of a function using gradient descent, one takes steps proportional to the negative of the gradient of the function at the current point.


![alt text](http://hmkcode.github.io/images/ai/bp_update_formula.png)

For example, to update <font color ="blue">w6</font>, we take the current <font color ="blue">w6</font>, and subtract the partial derivative of <b>error</b> function with respect to w6. Optionally, we multiply the derivative of the error function by a selected number to make sure that the new updated <b>weight</b> is minimizing the error function; this number is called <b>learning rate</b>.

![alt text](http://hmkcode.github.io/images/ai/bp_w6_update.png)

The derivation of the error function is evaluated by applying the chain rule as following

![alt text](http://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w6.png)

So to update <font color="blue">w6</font> we can apply the following formula

![alt text](http://hmkcode.github.io/images/ai/bp_w6_update_closed_form.png)

Similarly, we can derive the update formula for <font color="blue">w5</font> and any other weights existing between the output and the hidden layer.

![alt text](http://hmkcode.github.io/images/ai/bp_w5_update_closed_form.png)

However, when moving backward to update <font color="blue">w1, w2, w3</font> and <font color="blue">w4 </font>existing between input and hidden layer, the partial derivative for the error function with respect to<font colr="blue"> w1</font>, for example, will be as following.

![alt text](http://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w1.png)

We can find the update formula for the remaining weights <font colr="blue">w2, w3 </font>and <font color="blue">w4</font>  in the same way.

In summary, the update formulas for all weights will be as following:

![alt text](http://hmkcode.github.io/images/ai/bp_update_all_weights.png)

We can rewrite the update formulas in matrices as following
![alt text](http://hmkcode.github.io/images/ai/bp_update_all_weights_matrix.png)

##Backward Pass

Using derived formulas we can find the new <b>weights</b>.

><b> Learning rate</b>: is a hyperparameter which means that we need to manually guess its value.

![alt text](https://github.com/prajnaraipn7/img/blob/master/fi.JPG?raw=true)


$$
\begin{bmatrix}
w5\\
w6\\
\end{bmatrix}
=
\begin{bmatrix}
.17\\
.12\\
\end{bmatrix}
-0.05(-0.85)
\begin{bmatrix}
.46\\
.62\\
\end{bmatrix}
=
\begin{bmatrix}
.17\\
.12\\
\end{bmatrix}
-
\begin{bmatrix}
-0.019\\
-0.026\\
\end{bmatrix}
=
\begin{bmatrix}
0.19\\
0.15\\
\end{bmatrix}
$$

$$
\begin{bmatrix}
w1&w3\\
w2&w4\\
\end{bmatrix} 
= 
\begin{bmatrix}
.20&.16\\
.02&.10\\
\end{bmatrix} 
-0.05(-0.85)
\begin{bmatrix}
2\\
3\\
\end{bmatrix}
\begin{bmatrix}
.17&.12\\
\end{bmatrix}
=
\begin{bmatrix}
.20&.16\\
.02&.10\\
\end{bmatrix} 
-
\begin{bmatrix}
-0.014&-0.0102\\
-0.0216&-0.015\\
\end{bmatrix} 
=
\begin{bmatrix}
0.214&0.17\\
0.0416&0.115\\
\end{bmatrix} 
$$

Now, using the new <b>weights</b> we will repeat the <b>forward passed</b>

![alt text](https://github.com/prajnaraipn7/img/blob/master/gi.JPG?raw=true)

$$
\begin{bmatrix}
2&3\\
\end{bmatrix}
.\begin{bmatrix}
0.214&0.17\\
0.0416&0.115\\
\end{bmatrix} 
=
\begin{bmatrix}
0.55&0.68\\
\end{bmatrix}
.\begin{bmatrix}
0.19\\
0.15\\
\end{bmatrix} 
=
\begin{bmatrix}
.20\\
\end{bmatrix} 
$$


We can notice that the <b>prediction</b> <font color="blue">0.20 </font>is a little bit closer to <b>actual output</b> than the previously predicted one <font color="blue">0.15</font>. We can repeat the same process of backward and forward pass until error is close or equal to zero.



#2B Assignment

In [0]:
#forward pass with weights w1=.20,w2=.02,w3=.16,w4=.10,w5=.17,w6=.12
import numpy as np
inp=np.array([[2,3]])
wbh = np.array([[0.20,.16],[.02,.10]])
hid=np.dot(inp,wbh)
wah=np.array([[0.17],[0.12]])
out=np.dot(hid,wah)

In [0]:
out

array([[0.1526]])

In [0]:
#Calcualating the error
Actual =1
Error=(1/2)*(out[0][0]-Actual)**2


In [0]:
#Assuming the learning rate as 0.05, find the delta
lr=0.05
Delta=out[0][0]-Actual
ld= lr*Delta

In [0]:
#finding the better weights to further reduce the error 
bw56=wah-(np.transpose(hid)*ld)
bw1234=wbh-(np.dot(np.transpose(inp)*ld,np.transpose(wah)))


In [0]:
bw56

array([[0.1894902],
       [0.1462694]])

In [0]:
bw1234

array([[0.2144058, 0.1701688],
       [0.0416087, 0.1152532]])

In [0]:
#Performing forward pass with the new weights -fiding new output
nwhid=np.dot(inp,bw1234)
nout=np.dot(nwhid,bw56)

In [0]:
nout

array([[0.20526394]])